CREATE TABLE [dbo].[ALARMLOGS]
(
	[ID] VARCHAR(50) NULL, 
    [DATE] VARCHAR(50) NULL, 
    [FIRST ALARM] VARCHAR(50) NULL, 
    [ALARM RECTIFIED] VARCHAR(50) NULL, 
    [COMMENTS] VARCHAR(50) NULL 
)
